# KOMP_test


### The content of this folder

The materials listed in this folder are provided to generate graphs for manuscript "Sexual dimorphism of plasma metabolites in 30 KO mouse strains by multi-platform mass spectrometry analysis"

Note: 
1. Folders are neither linear nor independent.

2. If you want to see the raw datafiles, please contact the author or see online puclication.

Summary output files

1.	Supplementary Data 1.xlsx is the raw metabolomics data file for 220 mice (wildtype & KOs) and was used for plotting Figure 3d-3f, Supplementary Figure 1a, and Supplementary Figure 3.
2.  Supplementary Data 2.xlsx is the raw phenotype data file extracted from IMPC database for 220 mice (wildtype & KOs), and was used for plotting Supplementary Figure 2b.
3.  Supplementary Data 3.xlsx was generated by analyzing metabolomics data in WT mice; 
    (Sheet: "1_no bodyweight adjusted") was used for Figure 2a, 2b, 2d & 2e;.
    (Sheet: "2_after bw adjusted") was used for Supplementary Figure 2a, 2b, 2d & 2e.
4.  Supplementary Data 4.xlsx was generated by analyzing IMPC Phenotype data in WT mice;
    (Sheet: "no bodyweight adjusted") was used for Figure 1c;
    (Sheet: "after bw adjusted") was used for Supplementary Figure 2c & 2f.
5.  Supplementary Data 5.xlsx was generated by analyzing metabolomics data comparing KO mouse with WT mice;
    (Sheet: "classification_KO metabolomics_") list the results for each KO strain with pvalue_Stage1 (genotype effect) < 0.05;
    (Sheet: "summary_KO metabolomics") was used for Figure 3a;
    (Sheet: "summary_KO metabolomics") & (Sheet: "summary exclude lipids") was used for Supplementary Figure 3c.
6.  Supplementary Data 6.xlsx was generated by analyzing IMPC Phenotype data comparing KO mouse with WT mice;
    (Sheet: "classification_KO phenotype") list the results for each KO strain with pvalue_Stage1 (genotype effect) < 0.05;
    (Sheet: "summary_KO phenotype") was used for Figure 3b;
    (Sheet: "classification_exclude weight") showed phenotypes with pvalue_Stage1 (genotype effect) < 0.05 but excluding body weight.

Below is a quick summary of generating the graphs.

   	Figure 2 (using R: Figure02) 
    Figure 3 (using R: Figure03) 
    Figure 4, 5, 6 (using R: Figure04-06)
    
    
    
    